export const challenges = [
	{
		id: 0,
		name: "Panic Function",
		description: [
			"Write a PANIC! function. The function should take in a sentence and return the same sentence in all caps with an exclamation point (!) at the end. Use JavaScript's built in string methods. ",
			"If the string is a phrase or sentence, add a 😱 emoji in between each word",
			"Example input: 'Hello'",
			"Example output: 'HELLO!'",
			"Example input: 'I'm almost out of coffee'",
			"Example output: 'I'M 😱 ALMOST 😱 OUT 😱 OF 😱 COFFEE!'",
			"Test your function",
			"console.log(panic('I'm almost out of coffee')); ",
			"console.log(panic('winter is coming'))",
		],
		methods: [".split()", " .join()"],
		img: "uuuuu",
		github:
			"https://github.com/IsabelTizon/js-challenges/blob/main/src/app/scrimba/exercises/panic.js",
	},
	{
		id: 1,
		name: "Whispering",
		description: [
			"Write a function `whisper` that takes in a sentence and returns a new sentence in all lowercase letters with 'shh...' at the beginning.",
			"The function should also remove an exclamation point at the end of the sentence, if there is one. ",
			"Example input: 'The KITTENS are SLEEPING!'",
			"Example output: 'shh... the kittens are sleeping'",
			"Test your function",
			"console.log(whisper('PLEASE STOP SHOUTING.'))",
			"console.log(whisper('MA'AM, this is a Wendy's!'))",
		],
		methods: ["endsWith", "slice"],
		img: "uuuuu",
		github:
			"https://github.com/IsabelTizon/js-challenges/blob/main/src/app/scrimba/exercises/whispering.js",
	},
	{
		id: 2,
		name: "tres",
		description: ["kkkkkkk", "kkkkkkk"],
		methods: ["sss", "hhhhhh"],
		img: "uuuuu",
		github: "ggggg",
	},
	{
		id: 3,
		name: "cuatro",
		description: ["kkkkkkk", "kkkkkkk"],
		methods: ["sss", "hhhhhh"],
		img: "uuuuu",
		github: "ggggg",
	},
	{
		id: 4,
		name: "cinco",
		description: ["kkkkkkk", "kkkkkkk"],
		methods: ["sss", "hhhhhh"],
		img: "uuuuu",
		github: "ggggg",
	},
];
